### ISSUE TITLE
https://avataaars.io/ is down

### ISSUE THREAD

**Issue by humaidk2** [maiconfriedel/random-avatar-generator#3]
Hi,

I wanted to let you know that avataaars server is down so this package doesn't work.
I liked the way you implemented this package, 
I think it might be a good idea to generate he avatar using an svg for better performance
similar to this package [avataars-generator](https://github.com/fangpenlin/avataaars-generator)
^I'm sure you can extract some logic from that 
what do you think?

**Comment by maiconfriedel** [comment]
https://avataaars.io/ is working fine now
